In [2]:
import numpy as np
import pandas as pd
from itertools import chain
import datetime

In [24]:
# read the scraped data from csv files to dataframe
#cuisine=pd.read_csv('restaurant_info.csv')
#cuisine

restaurant_info=pd.read_csv('restaurant_info_additional.csv',dtype={'average_cost':np.object})
restaurant_info

,address,postal_code,rest_name,average_cost,additional_info,rating
0,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,$75 for two people (approx.)\nFOR DINNER MENU\...,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3/5
1,"11 Madison Avenue, New York, NY 10010",NY 10010,Eleven Madison Park,$600 for two people (approx.),"['Full Bar Available', 'Farm-to-Table', 'Miche...",4.7/5
2,"225 E 60th Street, New York, NY 10022",NY 10022,Serendipity 3,$75 for two people (approx.),['Desserts and Bakes'],4.3/5
3,"314 W 11th Street, New York, NY 10014",NY 10014,The Spotted Pig,$70 for two people (approx.) with alcohol,"['Full Bar Available', 'Michelin Starred', 'Br...",4.6/5
4,"56 9th Avenue, New York, NY 10011",NY 10011,Old Homestead Steakhouse,$140 for two people (approx.)\nFOR DINNER MENU...,"['Takeout Available', 'Full Bar Available', 'O...",4.0/5
5,"Madison Square Park, 23rd & Madison, New York,...",NY 10010,Shake Shack,$30 for two people (approx.),"['Takeout Available', 'Wine and Beer', 'Outdoo...",4.9/5
6,"125 W 55th Street, New York, NY 10019",NY 10019,Estiatorio Milos,$250 for two people (approx.)\nFOR DINNER MENU...,"['Serves Alcohol', 'Lunch Menu']",4.1/5
7,"8801 3rd Avenue, Brooklyn, NY 11209",NY 11209,Cebu,$80 for two people (approx.)\nFOR DINNER MENU\...,"['Takeout Available', 'Full Bar Available', 'O...",4.0/5
8,"375 Greenwich Street, New York, NY 10013",NY 10013,Tribeca Grill,$75 for two people (approx.),"['Takeout Available', 'Wine']",3.9/5
9,"16 Bank Street, New York, NY 10014",NY 10014,The Waverly Inn and Garden,$120 for two people (approx.) with alcohol,"['Takeout Available', 'Full Bar Available', 'O...",3.7/5
10,"55 3rd Avenue, New York, NY 10003",NY 10003,The Smith,$90 for two people (approx.)\nFOR DINNER MENU\...,"['Breakfast', 'Delivery', 'Takeout Available',...",4.2/5
11,"1420 3rd Avenue, New York, NY 10028",NY 10028,Nancy Lee's Pig Heaven,$60 for two people (approx.),"['Delivery', 'Takeout Available', 'Serves Alco...",3.8/5
12,"62-29 Roosevelt Avenue, Queens, NY 11377",NY 11377,Jollibee,$20 for two people (approx.),['Takeout Available'],3.6/5
13,"900 7th Avenue, New York, NY 10019",NY 10019,Trattoria Dell'Arte,$120 for two people (approx.)\nFOR DINNER MENU...,"['Takeout Available', 'Serves Alcohol', 'Outdo...",4.3/5
14,"377 Greenwich Street, New York, NY 10013",NY 10013,Locanda Verde,$100 for two people (approx.)\nFOR DINNER MENU...,"['Breakfast', 'Takeout Available', 'Wine', 'Ou...",4.4/5
15,"2370 Belmont Avenue, Bronx, NY 10458",NY 10458,Antonio's Trattoria,$75 for two people (approx.)\nFOR DINNER MENU\...,"['Delivery', 'Takeout Available', 'Full Bar Av...",3.9/5
16,"119 7th Avenue, New York, NY 10011",NY 10011,Cafeteria,$75 for two people (approx.) with alcohol,"['Breakfast', 'Delivery', 'Takeout Available',...",4.3/5
17,"17 Orchard Street, New York, NY 10002",NY 10002,The Fat Radish,$75 for two people (approx.) with alcohol,"['Serves Alcohol', 'Nightlife', 'Farm-to-Table...",3.6/5
18,"105 Hudson Street, New York, NY 10013",NY 10013,Nobu,$250 for two people (approx.),"['Full Bar Available', 'Luxury Dining', 'Priva...",4.3/5
19,"430 Lafayette Street, New York, NY 10003",NY 10003,Indochine,$120 for two people (approx.),['Serves Alcohol'],3.6/5
20,"1900 Broadway, New York, NY 10023",NY 10023,Cafe Fiorello,$120 for two people (approx.)\nFOR DINNER MENU...,"['Takeout Available', 'Full Bar Available', 'O...",4.1/5
21,"20 E 60th Street, New York, NY 10021",NY 10021,Le Bilboquet,$80 for two people (approx.),"['Wine and Beer', 'Serves Cocktails', 'Outdoor...",3.7/5
22,"154 E 79th Street, New York, NY 10021",NY 10021,Candle 79,$75 for two people (approx.),"['Beer', 'Gluten Free Options', 'Vegetarian Fr...",4.1/5
23,"205 East Houston Street, New York, NY 10002",NY 10002,Katz's Delicatessen,$30 for two people (approx.),"['Breakfast', 'Takeout Available', 'Wine and B...",4.9/5
24,"14 Mott Street, New York, NY 10013",NY 10013,Ajisen Ramen,$30 for two people (approx.),"['Takeout Available', 'Serves Alcohol']",3.6/5
25,"230 5th Avenue, New York, NY 10001",NY 10001,230 Fifth,$120 for two people (approx.) with alcohol,"['Full Bar Available', 'Nightlife']",3.7/5
26,"171 Lafayette Avenue, Brooklyn, NY 11238",NY 11238,Olea,$80 for two people (approx.)\nFOR DINNER MENU\...,"['Breakfast', 'Takeout Available', 'Serves Alc...",4.2/5
27,"235 Mulberry Street, New York, NY 10012",NY 10012,Rubirosa,$85 for two people (approx.)\nFOR DINNER MENU\...,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0/5
28,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,$250 for two people (approx.)\nFOR DINNER MENU...,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9/5
29,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,$60 for two people (approx.),"['Takeout Available', 'Full Bar Available', 'S...",3.8/5

In [3]:
restaurant_info.dtypes

address            object
postal_code        object
rest_name          object
average_cost       object
additional_info    object
rating             object
dtype: object

In [25]:
# split columns
restaurant_info['rating'] = restaurant_info['rating'].str.split('/',1,expand=True)
restaurant_info['average_cost'] = restaurant_info['average_cost'].str.split(' ').str[0].str.lstrip('$z').astype(int)
restaurant_info['rating'] = restaurant_info['rating'].astype(float)
restaurant_info

,address,postal_code,rest_name,average_cost,additional_info,rating
0,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3
1,"11 Madison Avenue, New York, NY 10010",NY 10010,Eleven Madison Park,600,"['Full Bar Available', 'Farm-to-Table', 'Miche...",4.7
2,"225 E 60th Street, New York, NY 10022",NY 10022,Serendipity 3,75,['Desserts and Bakes'],4.3
3,"314 W 11th Street, New York, NY 10014",NY 10014,The Spotted Pig,70,"['Full Bar Available', 'Michelin Starred', 'Br...",4.6
4,"56 9th Avenue, New York, NY 10011",NY 10011,Old Homestead Steakhouse,140,"['Takeout Available', 'Full Bar Available', 'O...",4.0
5,"Madison Square Park, 23rd & Madison, New York,...",NY 10010,Shake Shack,30,"['Takeout Available', 'Wine and Beer', 'Outdoo...",4.9
6,"125 W 55th Street, New York, NY 10019",NY 10019,Estiatorio Milos,250,"['Serves Alcohol', 'Lunch Menu']",4.1
7,"8801 3rd Avenue, Brooklyn, NY 11209",NY 11209,Cebu,80,"['Takeout Available', 'Full Bar Available', 'O...",4.0
8,"375 Greenwich Street, New York, NY 10013",NY 10013,Tribeca Grill,75,"['Takeout Available', 'Wine']",3.9
9,"16 Bank Street, New York, NY 10014",NY 10014,The Waverly Inn and Garden,120,"['Takeout Available', 'Full Bar Available', 'O...",3.7
10,"55 3rd Avenue, New York, NY 10003",NY 10003,The Smith,90,"['Breakfast', 'Delivery', 'Takeout Available',...",4.2
11,"1420 3rd Avenue, New York, NY 10028",NY 10028,Nancy Lee's Pig Heaven,60,"['Delivery', 'Takeout Available', 'Serves Alco...",3.8
12,"62-29 Roosevelt Avenue, Queens, NY 11377",NY 11377,Jollibee,20,['Takeout Available'],3.6
13,"900 7th Avenue, New York, NY 10019",NY 10019,Trattoria Dell'Arte,120,"['Takeout Available', 'Serves Alcohol', 'Outdo...",4.3
14,"377 Greenwich Street, New York, NY 10013",NY 10013,Locanda Verde,100,"['Breakfast', 'Takeout Available', 'Wine', 'Ou...",4.4
15,"2370 Belmont Avenue, Bronx, NY 10458",NY 10458,Antonio's Trattoria,75,"['Delivery', 'Takeout Available', 'Full Bar Av...",3.9
16,"119 7th Avenue, New York, NY 10011",NY 10011,Cafeteria,75,"['Breakfast', 'Delivery', 'Takeout Available',...",4.3
17,"17 Orchard Street, New York, NY 10002",NY 10002,The Fat Radish,75,"['Serves Alcohol', 'Nightlife', 'Farm-to-Table...",3.6
18,"105 Hudson Street, New York, NY 10013",NY 10013,Nobu,250,"['Full Bar Available', 'Luxury Dining', 'Priva...",4.3
19,"430 Lafayette Street, New York, NY 10003",NY 10003,Indochine,120,['Serves Alcohol'],3.6
20,"1900 Broadway, New York, NY 10023",NY 10023,Cafe Fiorello,120,"['Takeout Available', 'Full Bar Available', 'O...",4.1
21,"20 E 60th Street, New York, NY 10021",NY 10021,Le Bilboquet,80,"['Wine and Beer', 'Serves Cocktails', 'Outdoor...",3.7
22,"154 E 79th Street, New York, NY 10021",NY 10021,Candle 79,75,"['Beer', 'Gluten Free Options', 'Vegetarian Fr...",4.1
23,"205 East Houston Street, New York, NY 10002",NY 10002,Katz's Delicatessen,30,"['Breakfast', 'Takeout Available', 'Wine and B...",4.9
24,"14 Mott Street, New York, NY 10013",NY 10013,Ajisen Ramen,30,"['Takeout Available', 'Serves Alcohol']",3.6
25,"230 5th Avenue, New York, NY 10001",NY 10001,230 Fifth,120,"['Full Bar Available', 'Nightlife']",3.7
26,"171 Lafayette Avenue, Brooklyn, NY 11238",NY 11238,Olea,80,"['Breakfast', 'Takeout Available', 'Serves Alc...",4.2
27,"235 Mulberry Street, New York, NY 10012",NY 10012,Rubirosa,85,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0
28,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9
29,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8

In [26]:
# define bins and create rating groups
bins=[0,2.0,4.0,4.5,5.0]
group_names=['poor','average','good','excellent']
restaurant_info['rating_category'] = pd.cut(restaurant_info['rating'],bins,labels=group_names,right=False).astype('category')
restaurant_info

,address,postal_code,rest_name,average_cost,additional_info,rating,rating_category
0,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good
1,"11 Madison Avenue, New York, NY 10010",NY 10010,Eleven Madison Park,600,"['Full Bar Available', 'Farm-to-Table', 'Miche...",4.7,excellent
2,"225 E 60th Street, New York, NY 10022",NY 10022,Serendipity 3,75,['Desserts and Bakes'],4.3,good
3,"314 W 11th Street, New York, NY 10014",NY 10014,The Spotted Pig,70,"['Full Bar Available', 'Michelin Starred', 'Br...",4.6,excellent
4,"56 9th Avenue, New York, NY 10011",NY 10011,Old Homestead Steakhouse,140,"['Takeout Available', 'Full Bar Available', 'O...",4.0,good
5,"Madison Square Park, 23rd & Madison, New York,...",NY 10010,Shake Shack,30,"['Takeout Available', 'Wine and Beer', 'Outdoo...",4.9,excellent
6,"125 W 55th Street, New York, NY 10019",NY 10019,Estiatorio Milos,250,"['Serves Alcohol', 'Lunch Menu']",4.1,good
7,"8801 3rd Avenue, Brooklyn, NY 11209",NY 11209,Cebu,80,"['Takeout Available', 'Full Bar Available', 'O...",4.0,good
8,"375 Greenwich Street, New York, NY 10013",NY 10013,Tribeca Grill,75,"['Takeout Available', 'Wine']",3.9,average
9,"16 Bank Street, New York, NY 10014",NY 10014,The Waverly Inn and Garden,120,"['Takeout Available', 'Full Bar Available', 'O...",3.7,average
10,"55 3rd Avenue, New York, NY 10003",NY 10003,The Smith,90,"['Breakfast', 'Delivery', 'Takeout Available',...",4.2,good
11,"1420 3rd Avenue, New York, NY 10028",NY 10028,Nancy Lee's Pig Heaven,60,"['Delivery', 'Takeout Available', 'Serves Alco...",3.8,average
12,"62-29 Roosevelt Avenue, Queens, NY 11377",NY 11377,Jollibee,20,['Takeout Available'],3.6,average
13,"900 7th Avenue, New York, NY 10019",NY 10019,Trattoria Dell'Arte,120,"['Takeout Available', 'Serves Alcohol', 'Outdo...",4.3,good
14,"377 Greenwich Street, New York, NY 10013",NY 10013,Locanda Verde,100,"['Breakfast', 'Takeout Available', 'Wine', 'Ou...",4.4,good
15,"2370 Belmont Avenue, Bronx, NY 10458",NY 10458,Antonio's Trattoria,75,"['Delivery', 'Takeout Available', 'Full Bar Av...",3.9,average
16,"119 7th Avenue, New York, NY 10011",NY 10011,Cafeteria,75,"['Breakfast', 'Delivery', 'Takeout Available',...",4.3,good
17,"17 Orchard Street, New York, NY 10002",NY 10002,The Fat Radish,75,"['Serves Alcohol', 'Nightlife', 'Farm-to-Table...",3.6,average
18,"105 Hudson Street, New York, NY 10013",NY 10013,Nobu,250,"['Full Bar Available', 'Luxury Dining', 'Priva...",4.3,good
19,"430 Lafayette Street, New York, NY 10003",NY 10003,Indochine,120,['Serves Alcohol'],3.6,average
20,"1900 Broadway, New York, NY 10023",NY 10023,Cafe Fiorello,120,"['Takeout Available', 'Full Bar Available', 'O...",4.1,good
21,"20 E 60th Street, New York, NY 10021",NY 10021,Le Bilboquet,80,"['Wine and Beer', 'Serves Cocktails', 'Outdoor...",3.7,average
22,"154 E 79th Street, New York, NY 10021",NY 10021,Candle 79,75,"['Beer', 'Gluten Free Options', 'Vegetarian Fr...",4.1,good
23,"205 East Houston Street, New York, NY 10002",NY 10002,Katz's Delicatessen,30,"['Breakfast', 'Takeout Available', 'Wine and B...",4.9,excellent
24,"14 Mott Street, New York, NY 10013",NY 10013,Ajisen Ramen,30,"['Takeout Available', 'Serves Alcohol']",3.6,average
25,"230 5th Avenue, New York, NY 10001",NY 10001,230 Fifth,120,"['Full Bar Available', 'Nightlife']",3.7,average
26,"171 Lafayette Avenue, Brooklyn, NY 11238",NY 11238,Olea,80,"['Breakfast', 'Takeout Available', 'Serves Alc...",4.2,good
27,"235 Mulberry Street, New York, NY 10012",NY 10012,Rubirosa,85,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0,good
28,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average
29,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average

In [120]:
restaurant_info.to_csv("restaurant_info_manipulated", index=False)

In [104]:
cuisine['cuisine'] = cuisine['cuisine'].apply(lambda x: x.split(','))
cuisine

             location             restaurant_name                     cuisine
0   GRAMERCY-FLATIRON           Union Square Cafe        [American,  Italian]
1   GRAMERCY-FLATIRON         Eleven Madison Park                  [American]
2     UPPER EAST SIDE               Serendipity 3                  [American]
3   GREENWICH VILLAGE             The Spotted Pig                  [American]
4   GREENWICH VILLAGE    Old Homestead Steakhouse                  [American]
5   GRAMERCY-FLATIRON                 Shake Shack                  [American]
6             MIDTOWN            Estiatorio Milos     [Greek,  Mediterranean]
7       FORT HAMILTON                        Cebu                  [American]
8             TRIBECA               Tribeca Grill  [American,  Mediterranean]
9   GREENWICH VILLAGE  The Waverly Inn and Garden                  [American]
10       EAST VILLAGE                   The Smith                  [American]
11    UPPER EAST SIDE      Nancy Lee's Pig Heaven           [Taiwanese,  BBQ]
12           WOODSIDE                    Jollibee                  [Filipino]
13            MIDTOWN         Trattoria Dell'Arte                   [Italian]
14            TRIBECA               Locanda Verde                   [Italian]
15            BELMONT         Antonio's Trattoria           [Italian,  Pizza]
16            CHELSEA                   Cafeteria                  [American]
17    LOWER EAST SIDE              The Fat Radish                   [British]
18            TRIBECA                        Nobu                  [Japanese]
19  GREENWICH VILLAGE                   Indochine       [Vietnamese,  French]
20     LINCOLN SQUARE               Cafe Fiorello        [American,  Italian]
21    UPPER EAST SIDE                Le Bilboquet            [French,  Cajun]
22    UPPER EAST SIDE                   Candle 79                  [American]
23    LOWER EAST SIDE         Katz's Delicatessen                  [Sandwich]
24    LOWER EAST SIDE                Ajisen Ramen                  [Japanese]
25  GRAMERCY-FLATIRON                   230 Fifth                   [BarFood]
26        FORT GREENE                        Olea     [Mediterranean,  Tapas]
27    LOWER EAST SIDE                    Rubirosa            [Italian, Pizza]
28            MIDTOWN               La Grenouille                    [French]
29           GRAMERCY              Miss Korea BBQ              [Korean,  BBQ]

In [105]:
cuisine.cuisine

index=0
lst=[]

for i in cuisine.cuisine:
    lst.extend(map(lambda x: [index, x], i))
    index += 1
cuisine_sep = pd.DataFrame(lst,columns=['index','cuisine'])
print (cuisine_sep)

    index         cuisine
0       0        American
1       0         Italian
2       1        American
3       2        American
4       3        American
5       4        American
6       5        American
7       6           Greek
8       6   Mediterranean
9       7        American
10      8        American
11      8   Mediterranean
12      9        American
13     10        American
14     11       Taiwanese
15     11             BBQ
16     12        Filipino
17     13         Italian
18     14         Italian
19     15         Italian
20     15           Pizza
21     16        American
22     17         British
23     18        Japanese
24     19      Vietnamese
25     19          French
26     20        American
27     20         Italian
28     21          French
29     21           Cajun
30     22        American
31     23        Sandwich
32     24        Japanese
33     25         BarFood
34     26   Mediterranean
35     26           Tapas
36     27         Italian
37     27           Pizza
38     28          French
39     29          Korean
40     29             BBQ

In [106]:
# Merge with cuisine
cuisine=pd.merge(cuisine.drop('cuisine',axis=1),cuisine_sep, left_index=True,right_on='index')
cuisine=cuisine.drop('index',axis=1)
cuisine

             location             restaurant_name         cuisine
0   GRAMERCY-FLATIRON           Union Square Cafe        American
1   GRAMERCY-FLATIRON           Union Square Cafe         Italian
2   GRAMERCY-FLATIRON         Eleven Madison Park        American
3     UPPER EAST SIDE               Serendipity 3        American
4   GREENWICH VILLAGE             The Spotted Pig        American
5   GREENWICH VILLAGE    Old Homestead Steakhouse        American
6   GRAMERCY-FLATIRON                 Shake Shack        American
7             MIDTOWN            Estiatorio Milos           Greek
8             MIDTOWN            Estiatorio Milos   Mediterranean
9       FORT HAMILTON                        Cebu        American
10            TRIBECA               Tribeca Grill        American
11            TRIBECA               Tribeca Grill   Mediterranean
12  GREENWICH VILLAGE  The Waverly Inn and Garden        American
13       EAST VILLAGE                   The Smith        American
14    UPPER EAST SIDE      Nancy Lee's Pig Heaven       Taiwanese
15    UPPER EAST SIDE      Nancy Lee's Pig Heaven             BBQ
16           WOODSIDE                    Jollibee        Filipino
17            MIDTOWN         Trattoria Dell'Arte         Italian
18            TRIBECA               Locanda Verde         Italian
19            BELMONT         Antonio's Trattoria         Italian
20            BELMONT         Antonio's Trattoria           Pizza
21            CHELSEA                   Cafeteria        American
22    LOWER EAST SIDE              The Fat Radish         British
23            TRIBECA                        Nobu        Japanese
24  GREENWICH VILLAGE                   Indochine      Vietnamese
25  GREENWICH VILLAGE                   Indochine          French
26     LINCOLN SQUARE               Cafe Fiorello        American
27     LINCOLN SQUARE               Cafe Fiorello         Italian
28    UPPER EAST SIDE                Le Bilboquet          French
29    UPPER EAST SIDE                Le Bilboquet           Cajun
30    UPPER EAST SIDE                   Candle 79        American
31    LOWER EAST SIDE         Katz's Delicatessen        Sandwich
32    LOWER EAST SIDE                Ajisen Ramen        Japanese
33  GRAMERCY-FLATIRON                   230 Fifth         BarFood
34        FORT GREENE                        Olea   Mediterranean
35        FORT GREENE                        Olea           Tapas
36    LOWER EAST SIDE                    Rubirosa         Italian
37    LOWER EAST SIDE                    Rubirosa           Pizza
38            MIDTOWN               La Grenouille          French
39           GRAMERCY              Miss Korea BBQ          Korean
40           GRAMERCY              Miss Korea BBQ             BBQ

In [108]:
restaurant = pd.merge(cuisine,restaurant_info, how='inner',left_on='restaurant_name',right_on='rest_name')

In [109]:
restaurant = restaurant.drop('rest_name',axis=1)
restaurant

,location,restaurant_name,cuisine,address,postal_code,average_cost,additional_info,rating,rating_category
0,GRAMERCY-FLATIRON,Union Square Cafe,American,"16th Street, New York, NY 10003",NY 10003,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good
1,GRAMERCY-FLATIRON,Union Square Cafe,Italian,"16th Street, New York, NY 10003",NY 10003,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good
2,GRAMERCY-FLATIRON,Eleven Madison Park,American,"11 Madison Avenue, New York, NY 10010",NY 10010,600,"['Full Bar Available', 'Farm-to-Table', 'Miche...",4.7,excellent
3,UPPER EAST SIDE,Serendipity 3,American,"225 E 60th Street, New York, NY 10022",NY 10022,75,['Desserts and Bakes'],4.3,good
4,GREENWICH VILLAGE,The Spotted Pig,American,"314 W 11th Street, New York, NY 10014",NY 10014,70,"['Full Bar Available', 'Michelin Starred', 'Br...",4.6,excellent
5,GREENWICH VILLAGE,Old Homestead Steakhouse,American,"56 9th Avenue, New York, NY 10011",NY 10011,140,"['Takeout Available', 'Full Bar Available', 'O...",4.0,good
6,GRAMERCY-FLATIRON,Shake Shack,American,"Madison Square Park, 23rd & Madison, New York,...",NY 10010,30,"['Takeout Available', 'Wine and Beer', 'Outdoo...",4.9,excellent
7,MIDTOWN,Estiatorio Milos,Greek,"125 W 55th Street, New York, NY 10019",NY 10019,250,"['Serves Alcohol', 'Lunch Menu']",4.1,good
8,MIDTOWN,Estiatorio Milos,Mediterranean,"125 W 55th Street, New York, NY 10019",NY 10019,250,"['Serves Alcohol', 'Lunch Menu']",4.1,good
9,FORT HAMILTON,Cebu,American,"8801 3rd Avenue, Brooklyn, NY 11209",NY 11209,80,"['Takeout Available', 'Full Bar Available', 'O...",4.0,good
10,TRIBECA,Tribeca Grill,American,"375 Greenwich Street, New York, NY 10013",NY 10013,75,"['Takeout Available', 'Wine']",3.9,average
11,TRIBECA,Tribeca Grill,Mediterranean,"375 Greenwich Street, New York, NY 10013",NY 10013,75,"['Takeout Available', 'Wine']",3.9,average
12,GREENWICH VILLAGE,The Waverly Inn and Garden,American,"16 Bank Street, New York, NY 10014",NY 10014,120,"['Takeout Available', 'Full Bar Available', 'O...",3.7,average
13,EAST VILLAGE,The Smith,American,"55 3rd Avenue, New York, NY 10003",NY 10003,90,"['Breakfast', 'Delivery', 'Takeout Available',...",4.2,good
14,UPPER EAST SIDE,Nancy Lee's Pig Heaven,Taiwanese,"1420 3rd Avenue, New York, NY 10028",NY 10028,60,"['Delivery', 'Takeout Available', 'Serves Alco...",3.8,average
15,UPPER EAST SIDE,Nancy Lee's Pig Heaven,BBQ,"1420 3rd Avenue, New York, NY 10028",NY 10028,60,"['Delivery', 'Takeout Available', 'Serves Alco...",3.8,average
16,WOODSIDE,Jollibee,Filipino,"62-29 Roosevelt Avenue, Queens, NY 11377",NY 11377,20,['Takeout Available'],3.6,average
17,MIDTOWN,Trattoria Dell'Arte,Italian,"900 7th Avenue, New York, NY 10019",NY 10019,120,"['Takeout Available', 'Serves Alcohol', 'Outdo...",4.3,good
18,TRIBECA,Locanda Verde,Italian,"377 Greenwich Street, New York, NY 10013",NY 10013,100,"['Breakfast', 'Takeout Available', 'Wine', 'Ou...",4.4,good
19,BELMONT,Antonio's Trattoria,Italian,"2370 Belmont Avenue, Bronx, NY 10458",NY 10458,75,"['Delivery', 'Takeout Available', 'Full Bar Av...",3.9,average
20,BELMONT,Antonio's Trattoria,Pizza,"2370 Belmont Avenue, Bronx, NY 10458",NY 10458,75,"['Delivery', 'Takeout Available', 'Full Bar Av...",3.9,average
21,CHELSEA,Cafeteria,American,"119 7th Avenue, New York, NY 10011",NY 10011,75,"['Breakfast', 'Delivery', 'Takeout Available',...",4.3,good
22,LOWER EAST SIDE,The Fat Radish,British,"17 Orchard Street, New York, NY 10002",NY 10002,75,"['Serves Alcohol', 'Nightlife', 'Farm-to-Table...",3.6,average
23,TRIBECA,Nobu,Japanese,"105 Hudson Street, New York, NY 10013",NY 10013,250,"['Full Bar Available', 'Luxury Dining', 'Priva...",4.3,good
24,GREENWICH VILLAGE,Indochine,Vietnamese,"430 Lafayette Street, New York, NY 10003",NY 10003,120,['Serves Alcohol'],3.6,average
25,GREENWICH VILLAGE,Indochine,French,"430 Lafayette Street, New York, NY 10003",NY 10003,120,['Serves Alcohol'],3.6,average
26,LINCOLN SQUARE,Cafe Fiorello,American,"1900 Broadway, New York, NY 10023",NY 10023,120,"['Takeout Available', 'Full Bar Available', 'O...",4.1,good
27,LINCOLN SQUARE,Cafe Fiorello,Italian,"1900 Broadway, New York, NY 10023",NY 10023,120,"['Takeout Available', 'Full Bar Available', 'O...",4.1,good
28,UPPER EAST SIDE,Le Bilboquet,French,"20 E 60th Street, New York, NY 10021",NY 10021,80,"['Wine and Beer', 'Serves Cocktails', 'Outdoor...",3.7,average
29,UPPER EAST SIDE,Le Bilboquet,Cajun,"20 E 60th Street, New York, NY 10021",NY 10021,80,"['Wine and Beer', 'Serves Cocktails', 'Outdoor...",3.7,average
30,UPPER EAST SIDE,Candle 79,American,"154 E 79th Street, New York, NY 10021",NY 10021,75,"['Beer', 'Gluten Free Options', 'Vegetarian Fr...",4.1,good
31,LOWER EAST SIDE,Katz's Delicatessen,Sandwich,"205 East Houston Street, New York, NY 10002",NY 10002,30,"['Breakfast', 'Takeout Available', 'Wine and B...",4.9,excellent
32,LOWER EAST SIDE,Ajisen Ramen,Japanese,"14 Mott Street, New York, NY 10013",NY 10013,30,"['Takeout Available', 'Serves Alcohol']",3.6,average
33,GRAMERCY-FLATIRON,230 Fifth,BarFood,"230 5th Avenue, New York, NY 10001",NY 10001,120,"['Full Bar Available', 'Nightlife']",3.7,average
34,FORT GREENE,Olea,Mediterranean,"171 Lafayette Avenue, Brooklyn, NY 11238",NY 11238,80,"['Breakfast', 'Takeout Available', 'Serves Alc...",4.2,good
35,FORT GREENE,Olea,Tapas,"171 Lafayette Avenue, Brooklyn, NY 11238",NY 11238,80,"['Breakfast', 'Takeout Available', 'Serves Alc...",4.2,good
36,LOWER EAST SIDE,Rubirosa,Italian,"235 Mulberry Street, New York, NY 10012",NY 10012,85,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0,good
37,LOWER EAST SIDE,Rubirosa,Pizza,"235 Mulberry Street, New York, NY 10012",NY 10012,85,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0,good
38,MIDTOWN,La Grenouille,French,"3 E 52nd Street, New York, NY 10022",NY 10022,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average
39,GRAMERCY,Miss Korea BBQ,Korean,"10 W 32nd Street, New York, NY 10001",NY 10001,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average
40,GRAMERCY,Miss Korea BBQ,BBQ,"10 W 32nd Street, New York, NY 10001",NY 10001,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average

In [42]:
restaurant.dtypes

location            object
restaurant_name     object
cuisine             object
address             object
postal_code         object
rest_name           object
average_cost         int32
additional_info     object
rating             float64
dtype: object

In [117]:

restaurant.to_csv('restaurants_cuisine.csv',index=False)

In [27]:
restaurants_review = pd.read_csv('restaurant_review.csv', encoding='ISO-8859-1')

In [28]:
restaurants_review

,review,rest_name,review_date_time,user_name
0,NaN,Union Square Cafe,6-Nov-15,Foodie 411
1,RATED\n Really like this place. Great atmosph...,Union Square Cafe,20-Oct-15,Hung Dong Long
2,RATED\n Another place downtown that has seen ...,Union Square Cafe,18-Jun-15,Aditya Dhillon
3,After my write-up of my visit to Union Square ...,Union Square Cafe,8-Mar-15,Bonnie Tandy Leblang - BITE OF THE BEST
4,Great pork ravioli. Over the weekend I had the...,Union Square Cafe,19-Jan-15,Khsu77
5,"...we ducked into the nearest cafe, and by caf...",Union Square Cafe,19-Nov-14,Champagnetwilight
6,NEGATIVE\n The place is cruising on its repu...,Union Square Cafe,2-Aug-14,Jlimes
7,This is part of a review of three burgers that...,Union Square Cafe,20-Jul-14,Ben Lee Kong
8,NEGATIVE\n What happened to service?. The fo...,Union Square Cafe,1-Apr-14,Carole
9,As I wrote earlier when I visited Union Square...,Union Square Cafe,18-Jan-14,Bonnie Tandy Leblang - BITE OF THE BEST
10,NaN,Union Square Cafe,10-Jan-14,DGrubs
11,NaN,Union Square Cafe,17-Aug-13,Bonnie Tandy Leblang - BITE OF THE BEST
12,NaN,Union Square Cafe,7-Aug-13,LK
13,POSITIVE\n This is great little place with v...,Union Square Cafe,2-Jun-13,Moose
14,POSITIVE\n Meal of the year.. From apps to d...,Union Square Cafe,26-Aug-12,AngryCitrus
15,"Why Come Here? Dinner with the parents, suitab...",Union Square Cafe,14-Jun-12,The Dishelin Guide
16,"Union Square Cafe is elegant, but completely c...",Union Square Cafe,18-Apr-12,FreeFoodBoston
17,The trout was standard (although it did not ta...,Union Square Cafe,28-Mar-12,Grace Yang
18,"Opened in 1985, Danny Meyer's first restaurant...",Union Square Cafe,22-Feb-12,Eat The City
19,"I don't often order chicken, but when I know i...",Union Square Cafe,22-Jan-12,Newbie Foodies
20,NaN,Union Square Cafe,16-Oct-11,Chop Chop
21,POSITIVE\n Lovely lunch. Lunched here on hol...,Union Square Cafe,19-Sep-11,Scarlett
22,"...Grilled trout with green bean salad, crispy...",Union Square Cafe,27-Jul-11,Lauren
23,"Well priced, well fed and EXTREMELY well serve...",Union Square Cafe,20-Apr-11,Fritosandfoiegras
24,"Great food, atomsphere, and service. Recommended.",Union Square Cafe,8-Apr-11,Jack Morris
25,"POSITIVE\n One, well, 2 1/2 words: Good and ...",Union Square Cafe,25-Feb-11,Jtc9826
26,In today's economy fraught with economic uncer...,Union Square Cafe,21-Oct-10,ChiefHDB
27,"Union Square Café is a NYC institution, a plac...",Union Square Cafe,14-Oct-10,Evan H
28,NaN,Union Square Cafe,14-Oct-10,Evan H
29,My father is turning the ripe age of 55 today ...,Union Square Cafe,11-Oct-10,Mr. Micro
...,...,...,...,...
1828,"POSITIVE\n The service is great, as advertis...",La Grenouille,16-Mar-14,Brent Byers
1829,POSITIVE\n Wonderful restaurant. Classic New...,La Grenouille,25-Oct-13,Tom Mason
1830,POSITIVE\n We went there to celebrate my hus...,La Grenouille,2-Oct-13,M And D On The Road
1831,POSITIVE\n Nearly flawless. My wife and I at...,La Grenouille,23-Jul-11,Kory Warr
1832,NaN,La Grenouille,29-Jun-11,FredB
1833,Our first act: La Grenouille . This almost 50 ...,La Grenouille,28-Apr-11,Eating Around DC
1834,NaN,La Grenouille,23-Nov-10,Kd
1835,"POSITIVE\n Class. Top to bottom, an excellen...",La Grenouille,5-Oct-09,JW
1836,POSITIVE\n Ma chérie. Just plain old school ...,La Grenouille,3-May-09,Shanghaiist
1837,POSITIVE\n By far the best restaurant in new...,La Grenouille,17-Mar-09,TCoop92
1838,For a recent special occasion (this blogger's ...,La Grenouille,19-Feb-09,Miranda
1839,POSITIVE\n Merci. That is all i could keep s...,La Grenouille,6-Feb-09,Pumpkin Gnocchi
1840,POSITIVE\n PERFECTION. La Grenouille is hand...,La Grenouille,28-May-08,Cstrum
1841,Checked out La Grenouille with M today for lun...,La Grenouille,28-Jan-08,Oeno:li..cious
1842,RATED\n On our quest to get some soup and/or ...,Miss Korea BBQ,19-Sep-16,The Buppie Foodie Media Group
1843,RATED\n I like the atmosphere of this restaur...,Miss Korea BBQ,15-Jul-16,Blue_lagoon
1844,RATED\n Came here twice. Both on busy Friday'...,Miss Korea BBQ,12-Mar-16,Shivanjali
1845,RATED\n Came here for lunch on Wednesday with...,Miss Korea BBQ,14-Dec-15,Sheena
1846,RATED\n Ooh. Everytime I'm in Manhattan i com...,Miss Korea BBQ,12-Dec-15,Korean Food Monster
1847,RATED\n I ordered the Jopchae (sea food Jopch...,Miss Korea BBQ,20-Sep-15,Ali Khan
1848,NaN,Miss Korea BBQ,25-Jun-15,Alex Chester
1849,RATED\n Good food. Expensive but great atmosp...,Miss Korea BBQ,2-Jun-15,Victor Tran
1850,... brought little side dishes (known as banch...,Miss Korea BBQ,1-Apr-14,Long Live Feasts
1851,They do hot pot cooking at the table with a mi...,Miss Korea BBQ,17-Aug-13,DGrubs
1852,NaN,Miss Korea BBQ,15-Jan-13,I Just Want To Eat
1853,Amazing food and fantastic service!. There are...,Miss Korea BBQ,6-Jul-12,Anna
1854,Had a few out-of-towners to entertain and I wa...,Miss Korea BBQ,25-Jun-12,Newbie Foodies
1855,You could tell this restaurant was authentic a...,Miss Korea BBQ,16-Oct-11,Acfong
1856,NaN,Miss Korea BBQ,5-Oct-11,Feisty Foodie
1857,The quality of meat was actually better than I...,Miss Korea BBQ,15-Sep-11,Grace Yang

In [79]:
restaurants_review.isnull().sum()

review              145
rest_name             0
review_date_time      0
user_name             0
dtype: int64

In [81]:
#no. of missing per row
np.sum(restaurants_review.isnull(),axis=1)
restaurant_review.dtypes

review              object
rest_name           object
review_date_time    object
user_name           object
dtype: object

In [ ]:
#datetime column
def convert_date(x):
    if x.str.find("months ago")!=-1:
        n=x.str[0:2]
        return datetime.now()-timedelts(months=n)
    elif x.str.find("days ago")!=-1:
        n = x.str[0:2]
        return datetime.now()-timedelts(days=n)
    else:
        return x.astype(datetime)

In [29]:
restaurants_reviews = pd.merge(restaurant_info, restaurants_review, how= 'inner', left_on='rest_name',right_on='rest_name')

In [114]:
#restaurants_reviews= restaurants_reviews.drop('rest_name',axis=1)

In [31]:
restaurants_reviews=restaurants_reviews.dropna()
restaurants_reviews

,address,postal_code,rest_name,average_cost,additional_info,rating,rating_category,review,review_date_time,user_name
1,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,RATED\n Really like this place. Great atmosph...,20-Oct-15,Hung Dong Long
2,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,RATED\n Another place downtown that has seen ...,18-Jun-15,Aditya Dhillon
3,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,After my write-up of my visit to Union Square ...,8-Mar-15,Bonnie Tandy Leblang - BITE OF THE BEST
4,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,Great pork ravioli. Over the weekend I had the...,19-Jan-15,Khsu77
5,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"...we ducked into the nearest cafe, and by caf...",19-Nov-14,Champagnetwilight
6,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,NEGATIVE\n The place is cruising on its repu...,2-Aug-14,Jlimes
7,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,This is part of a review of three burgers that...,20-Jul-14,Ben Lee Kong
8,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,NEGATIVE\n What happened to service?. The fo...,1-Apr-14,Carole
9,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,As I wrote earlier when I visited Union Square...,18-Jan-14,Bonnie Tandy Leblang - BITE OF THE BEST
13,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,POSITIVE\n This is great little place with v...,2-Jun-13,Moose
14,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,POSITIVE\n Meal of the year.. From apps to d...,26-Aug-12,AngryCitrus
15,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"Why Come Here? Dinner with the parents, suitab...",14-Jun-12,The Dishelin Guide
16,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"Union Square Cafe is elegant, but completely c...",18-Apr-12,FreeFoodBoston
17,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,The trout was standard (although it did not ta...,28-Mar-12,Grace Yang
18,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"Opened in 1985, Danny Meyer's first restaurant...",22-Feb-12,Eat The City
19,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"I don't often order chicken, but when I know i...",22-Jan-12,Newbie Foodies
21,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,POSITIVE\n Lovely lunch. Lunched here on hol...,19-Sep-11,Scarlett
22,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"...Grilled trout with green bean salad, crispy...",27-Jul-11,Lauren
23,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"Well priced, well fed and EXTREMELY well serve...",20-Apr-11,Fritosandfoiegras
24,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"Great food, atomsphere, and service. Recommended.",8-Apr-11,Jack Morris
25,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"POSITIVE\n One, well, 2 1/2 words: Good and ...",25-Feb-11,Jtc9826
26,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,In today's economy fraught with economic uncer...,21-Oct-10,ChiefHDB
27,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,"Union Square Café is a NYC institution, a plac...",14-Oct-10,Evan H
29,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,My father is turning the ripe age of 55 today ...,11-Oct-10,Mr. Micro
30,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,POSITIVE\n Had a business lunch here recentl...,25-Aug-10,John Korolow
31,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,NEGATIVE\n Hurried and unfriendly service. D...,13-Apr-10,Neil.schaefer
33,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,POSITIVE\n Wonderful menu and perfectly pres...,9-Dec-09,Foodimentary
34,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,Fabulous!!!. A trip to NYC for foodies would n...,6-Dec-09,Charlette
35,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,NEGATIVE\n So so SO STALE and the bartender ...,30-Sep-09,Seanin
36,"16th Street, New York, NY 10003",NY 10003,Union Square Cafe,75,"['Full Bar Available', 'Nightlife', 'Wifi', 'L...",4.3,good,POSITIVE\n Love Hate Relationship. We have b...,2-Aug-09,Ron De Long
...,...,...,...,...,...,...,...,...,...,...
1821,"235 Mulberry Street, New York, NY 10012",NY 10012,Rubirosa,85,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0,good,"Just over a year ago, a Staten Island specialt...",4-Oct-11,ChiefHDB
1822,"235 Mulberry Street, New York, NY 10012",NY 10012,Rubirosa,85,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0,good,Considering how difficult it is to get a reser...,5-Sep-11,The Right Pick
1823,"235 Mulberry Street, New York, NY 10012",NY 10012,Rubirosa,85,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0,good,the initial draw is pizza with exceptionally t...,28-Apr-11,The Hungry Roach
1824,"235 Mulberry Street, New York, NY 10012",NY 10012,Rubirosa,85,"['Delivery', 'Takeout Available', 'Full Bar Av...",4.0,good,POSITIVE\n Delicious Pepperoni Pizza.,22-Feb-11,Rob Greis
1826,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,A simplistically pretty place with their beaut...,16-Mar-15,Bon Viveur
1828,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,"POSITIVE\n The service is great, as advertis...",16-Mar-14,Brent Byers
1829,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,POSITIVE\n Wonderful restaurant. Classic New...,25-Oct-13,Tom Mason
1830,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,POSITIVE\n We went there to celebrate my hus...,2-Oct-13,M And D On The Road
1831,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,POSITIVE\n Nearly flawless. My wife and I at...,23-Jul-11,Kory Warr
1833,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,Our first act: La Grenouille . This almost 50 ...,28-Apr-11,Eating Around DC
1835,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,"POSITIVE\n Class. Top to bottom, an excellen...",5-Oct-09,JW
1836,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,POSITIVE\n Ma chérie. Just plain old school ...,3-May-09,Shanghaiist
1837,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,POSITIVE\n By far the best restaurant in new...,17-Mar-09,TCoop92
1838,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,For a recent special occasion (this blogger's ...,19-Feb-09,Miranda
1839,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,POSITIVE\n Merci. That is all i could keep s...,6-Feb-09,Pumpkin Gnocchi
1840,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,POSITIVE\n PERFECTION. La Grenouille is hand...,28-May-08,Cstrum
1841,"3 E 52nd Street, New York, NY 10022",NY 10022,La Grenouille,250,"['Takeout Available', 'Serves Alcohol', 'Wifi'...",3.9,average,Checked out La Grenouille with M today for lun...,28-Jan-08,Oeno:li..cious
1842,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,RATED\n On our quest to get some soup and/or ...,19-Sep-16,The Buppie Foodie Media Group
1843,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,RATED\n I like the atmosphere of this restaur...,15-Jul-16,Blue_lagoon
1844,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,RATED\n Came here twice. Both on busy Friday'...,12-Mar-16,Shivanjali
1845,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,RATED\n Came here for lunch on Wednesday with...,14-Dec-15,Sheena
1846,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,RATED\n Ooh. Everytime I'm in Manhattan i com...,12-Dec-15,Korean Food Monster
1847,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,RATED\n I ordered the Jopchae (sea food Jopch...,20-Sep-15,Ali Khan
1849,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,RATED\n Good food. Expensive but great atmosp...,2-Jun-15,Victor Tran
1850,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,... brought little side dishes (known as banch...,1-Apr-14,Long Live Feasts
1851,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,They do hot pot cooking at the table with a mi...,17-Aug-13,DGrubs
1853,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,Amazing food and fantastic service!. There are...,6-Jul-12,Anna
1854,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,Had a few out-of-towners to entertain and I wa...,25-Jun-12,Newbie Foodies
1855,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,You could tell this restaurant was authentic a...,16-Oct-11,Acfong
1857,"10 W 32nd Street, New York, NY 10001",NY 10001,Miss Korea BBQ,60,"['Takeout Available', 'Full Bar Available', 'S...",3.8,average,The quality of meat was actually better than I...,15-Sep-11,Grace Yang

In [32]:
#copy dataframe to csv to be used for plotting
restaurants_reviews.to_csv("restaurants_reviews_manipulated.csv")